---
file_attributes:
  -
    description: sql/promscale_demo.sql
    end_time: 1649805122.01167
    start_time: 1649805115.6147
file_order:
  - sql/promscale_demo.sql
start_time: 1649805115
stop_time: 1649805122
