---
file_attributes:
  -
    description: sql/promscale_demo.sql
    end_time: 1649798440.3647
    start_time: 1649798436.00915
file_order:
  - sql/promscale_demo.sql
start_time: 1649798435
stop_time: 1649798440
